export const TOGGLE_BUTTON = "TOGGLE_BUTTON"
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const FETCH_USER = "FETCH_USER"
export const AUTH_ERROR = "AUTH_ERROR"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "SIGNIN_FAIL"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const SIGNOUT = "SIGNOUT"
